libp2p/test-plans

- dht/compositions/all-balsam-k8s.toml
- dht/compositions/all-both-k8s.toml
- dht/compositions/bootstrap-network-cypress-k8s.toml
- dht/compositions/find-provs-balsam-k8s.toml
- dht/compositions/find-provs-both-k8s.toml
- dht/compositions/find-provs-both-local.toml
- dht/compositions/find-provs-cypress-k8s.toml
- dht/compositions/find-provs-k8s.toml
- dht/compositions/find-provs.toml
- dht/compositions/gcp-balsam-k8s.toml
- dht/compositions/gcp-cypress-k8s.toml
This PR is addressing an issue described at https://github.com/libp2p/test-plans/issues/10 - seems like we are keeping private artifacts as part of our public composition files.
Generally we shouldn't need artifacts any more, since we have improved a lot the building and pushing of images in the last few releases of Testground. I believe artifacts were used heavily by @aschmahmann while Testground didn't have good support for caching and was making redundant pushes to remote registries.
cc @Drengot-p2p
> remove private artifacts

- ping/_compositions/go-rust-interop-latest.toml
- ping/_compositions/go-rust-interop.toml
- ping/_compositions/rust-cross-versions.toml
- ping/_compositions/rust.toml
Recent builds break because there is a version `0.47.0` in one of our rewrite strings,
- Demo run with a custom branch: https://github.com/libp2p/test-plans/runs/8087223516?check_suite_focus=true
> ping/_compositions/*: fix rust version rewrite

- ping/_compositions/go-rust-interop-latest.toml
Update the interop (latest) tests so that we build & test:
- latest released go version
- latest released rust version
- current branch (rust or go)
(before we would test against `master` branch for each of these projects).
> ping/_composition: use latest release in interop-latest

- .github/actions/setup-testground/action.yml
Rely on the (new) edge releases of Testground.
Setup Testground using a script that downloads the latest containers instead of rebuilding Testground every time.
Reduce Testground setup time from 5min to 46 seconds. (minus 4 minutes)
Which amounts to approx. 27% (simple tests) and 12% (large tests) of the CI runtime.
(using average times for now since this change is trivial)
|workflow                                |current|this PR|
|----------------------------------------|-----------------------|-----------------------|
|rust-libp2p ping - rust test with testground.|19 min (100% success)   |16 min (100% success)   |
|libp2p ping - go and rust test (all) with testground.|26 min (94% success)    |22 min (86% success)    |
|libp2p ping - go + rust test (latest) with testground.|17 min (100% …
> .github/actions/setup-testground: shortcircuit testground setup

- README.md
- ping/_compositions/go-rust-interop-latest.toml
- ping/_compositions/go-rust-interop.toml
- ping/_compositions/rust-cross-versions.toml
- ping/_compositions/rust.toml
- ping/rust/Cargo.toml
- ping/rust/src/main.rs
Fixes #43 
Problem definition:
- We want to give the `rust-libp2p` repository the ability to build and test their `master` branch (which is also used when testing fork and PRs).
- We want to protect other client-repositories (such as `go-libp2p`) from failure due to unchecked changes in the `rust-libp2p` repository.
The case we've seen with #43:
- A release happens in `rust-libp2p`,
- The version is bumped in the `master` branch
- Now the line `libp2pv0480 = { git= ... branch = master, version = 0.48.0}` breaks because the version cannot be found.
This is a valid change (the `rust-libp2p` didn't break the interop contract, they "just" updated versions) which broke the `go-libp2p` repository.
The way we implement compatibility/features flags with rust has two constraints:
- we can't use …
> ping/rust: remove the master dependency

- .github/actions/setup-testground/action.yml
- .github/workflows/run-composition.yml
fixes #39 
Use the `write-artifacts` option during the build.
With this option, Testground replaces the composition file with the one produced by the build step (template generation applied, build artifact set).
With this we:
- Never rebuild the containers, even on Docker cache miss,
- Can save the generated composition (templating applied) as a useful debug artifact
> .github/workflows: use write-artifacts and prevent rebuild

- ping/_compositions/go-rust-interop-latest.toml
- ping/_compositions/go-rust-interop.toml
- ping/_compositions/rust-cross-versions.toml
- ping/_compositions/rust.toml
- ping/rust/Cargo.lock
- ping/rust/Cargo.toml
- ping/rust/src/main.rs
See release of v0.48.0 in https://github.com/libp2p/rust-libp2p/pull/2869.
Master bump to v0.49.0 in https://github.com/libp2p/rust-libp2p/pull/2813
Followed the instructions on https://github.com/libp2p/test-plans#how-to-add-a-new-version-to-pingrust.
I skipped step (3), namely to run the new test on my local machine. As far as I can tell this is done on CI here already. Please correct me if I am wrong.
> ping/: Update to rust-libp2p release v0.48.0 and master v0.49.0

- DESIGN.md
- README.md
- ROADMAP.md
> Organization: add PROCESS.md and ROADMAP.md

- ping/_compositions/go-rust-interop-latest.toml
- ping/_compositions/go-rust-interop.toml
- ping/_compositions/rust-cross-versions.toml
- ping/_compositions/rust.toml
- ping/rust/Cargo.lock
- ping/rust/Cargo.toml
- ping/rust/src/main.rs
I am not sure if I did all of this right. I was a bit confused as to why there is seemingly so much duplication between the various `toml` files and whether they all need updating or not.
Hoping that CI here will tell me whether this works :D
Resolves #59.
> Update for rust-libp2p 0.49 release

- ping/rust/Cargo.lock
Updates dependency. In the hope to resolve conflict from https://github.com/libp2p/rust-libp2p/pull/2972/.
> ping/rust: Run cargo update

- ping/rust/Dockerfile
How about we build in debug mode **for now**.
```
+ I expect this to significantly reduce build times.
+ I doubt it slows down execution time. 
- In production, people run in release mode.
```
> ping/rust/Dockerfile: Build in debug mode instead of release mode

- ping/rust/Dockerfile
Otherwise the tests for https://github.com/libp2p/rust-libp2p/pull/3239 don't run.
> feat(ping/rust): bump Rust version of docker image to 1.65

- ping/go/compat/libp2p.v0.11.go
- ping/go/compat/libp2p.v0.17.go
- ping/go/compat/libp2p.v0.20.go
- ping/go/compat/libp2p.v0.22.go
- ping/go/main.go
There's a race issue where the local node emits the connected event, even if it doesn't have connections to all peers. This shows up in rust x go tests quite often.
Dealing with the shim layer was quite tough and involved a very slow feedback cycle. A simple `go build` doesn't work so you have to try against testground, which takes a while.
> Fix race in ping test case for Go

- multidim-interop/Makefile
- multidim-interop/js/v0.41/.dockerignore
- multidim-interop/js/v0.41/Dockerfile
- multidim-interop/js/v0.41/Makefile
- multidim-interop/js/v0.41/index.js
- multidim-interop/js/v0.41/package-lock.json
- multidim-interop/js/v0.41/package.json
- multidim-interop/versions.ts
You can test it yourself:
```
docker run --rm -it -p 6379:6379 redis/redis-stack
REDIS_ADDR=localhost:6379 ip="0.0.0.0" transport=ws security=noise muxer=mplex is_dialer="true" node index.js
REDIS_ADDR=localhost:6379 ip="0.0.0.0" transport=ws security=noise muxer=mplex is_dialer="false" node index.js
```
Haven't hooked it up to Go/Rust yet. Let me know if this PR suffices for you or if you need me to undertake some more steps.
In function of https://github.com/libp2p/test-plans/pull/97.
> add working ping test (js) or multidim-interop

- .github/workflows/update-badge.yml
Resolves https://github.com/libp2p/test-plans/pull/105#issuecomment-1386296268
@MarcoPolo Here's a working version of the update badge workflow. Tested here - https://github.com/galorgh/test-plans/actions/runs/3947334594 
I think the problem you were facing was caused by the fact that workflows triggered by `workflow_run` events have to be checked in to the default branch.
> feat: update README badge automatically

- multidim-interop/README.md
This defines what the test should do.
Note that none of the tests are currently conforming to this. Go prints to stdout; all the tests have the dialer also `RPUSH`; and none of them emit the structured JSON result.
Once we merge this, I'll update the existing tests.
> Add multidim-interop test spec

- .github/actions/run-interop-ping-test/action.yml
The `dockerBuildWrapper` script enables caching based on the `AWS_BUCKET` environment variable. When calling the `libp2p ping interop test` with a bucket name but no AWS credentials, this leads to the script enabling caching even though the workflow does not have access to AWS.
With this commit the environment variable `AWS_BUCKET` is only set when credentials are available and thus the `dockerBuildWrapper` script does not enable caching then workflow does nothave access to AWS.
Not deeply familiar with the setup. Let me know in case there are cleaner solutions.
See also https://github.com/libp2p/rust-libp2p/pull/3462 and the corresponding failure on its first commit.
> fix(aws): Only set bucket var when creds are available

- multidim-interop/go/v0.25/.gitignore
- multidim-interop/go/v0.25/Makefile
- multidim-interop/versions.ts
go-libp2p v0.25.1 is released. Lets add it to the tests.
This is almost identical to the rust test (checkout from repo and build the defined image)
> Add go-libp2p v0.25.1

- multidim-interop/versions.ts
I used the wrong reference here. I noticed today when my editor complained about unused imports.
> Fix image references

- multidim-interop/src/generator.ts
It's 10x smaller at 30MiB vs >500 MiB. We don't need or want the full "redis-stack" (comparison: https://redis.io/download/)
> Switch to redis:7-alpine

- multidim-interop/versions.ts
This commit disables the WebRTC tests for rust-libp2p v0.50.0 and v0.51.0 and chromium-js v0.41.0 and v0.42.0. Neither of these support the new `/webrtc-direct` (see https://github.com/multiformats/multiaddr/pull/150/#issuecomment-1468791586 for context on rename).
The missing support is blocking https://github.com/libp2p/rust-libp2p/pull/3688 namely to upgrade to using `/webrtc-direct`. (Note that this is only blocking CI. Users can already use `/webrtc-direct` with the latest released rust-libp2p.) More concretely the latest rust-libp2p `master` sends a `/webrtc-direct` address as the listener to the dialer. The dialer (i.e. the versions listed above) do not support `/webrtc-direct` and thus fail.
We will backport `/webrtc-direct` support to the rust-libp2p `v0.51.0` interop binary and …
> fix(versions): disable webrtc tests

- multidim-interop/src/compose-runner.ts
I believe the compose environment changed in CI. This changes the name of the compose file to not fail.
Closes https://github.com/libp2p/go-libp2p/issues/2244
> Sanitize name before saving to compose file

- multidim-interop/impl/go/v0.24/main.go
- multidim-interop/impl/rust/v0.51/Makefile
- multidim-interop/src/generator.ts
- multidim-interop/versions.ts
See https://github.com/multiformats/multiaddr/pull/150#issuecomment-1468791586 for context on discussion.
- Renames the `webrtc` transport identifier to `webrtc-direct`.
- Re-enables `webrtc-direct` support for rust-libp2p v0.51. Previously disabled in https://github.com/libp2p/test-plans/pull/160. See https://github.com/libp2p/rust-libp2p/pull/3781 for corresponding change on the rust-libp2p side.
- Leaves JS v0.41 and v0.42 untouched. To be done in a follow-up alongside JS dependency updates.
> fix(interop): rename `webrtc` to `webrtc-direct`

- multidim-interop/Makefile
- multidim-interop/helpers/cache.ts
- multidim-interop/impl/zig/.gitignore
- multidim-interop/impl/zig/v0.0.1/Makefile
- multidim-interop/versions.ts
closes #169. Two commits, the first reverts, the second prints some cpu info to help debug this issue if we see it again (I haven't changed how the libraries are compiled, but they should be using the clang defaults).
> Bring back zig-libp2p

- multidim-interop/impl/go/v0.27/Makefile
- multidim-interop/impl/zig/v0.0.1/Makefile
- multidim-interop/versions.ts
closes https://github.com/libp2p/test-plans/issues/176
> chore: Add go-libp2p v0.27.1 and v0.26.4, update zig-libp2p

- multidim-interop/impl/js/.gitignore
- multidim-interop/impl/js/v0.45/BrowserDockerfile
- multidim-interop/impl/js/v0.45/Dockerfile
- multidim-interop/impl/js/v0.45/Makefile
- multidim-interop/versions.ts
Uses the new in-repo test to test js-libp2p. 
Note some of the build steps are copied here because we actually want a slightly different build setup. We want to support running `make` and it building in a reproducible way on both MacOS and Linux. In the js-libp2p repo, we fetch node_modules in the CI context (not docker) to get a slight speed up. Here we do `npm i` within the docker build process.
This won't slow us down here however because we can cache these builds. That's not the case in the js-libp2p head builds when you're always building a new head.
> Add js-libp2p v0.45.0

- multidim-interop/src/generator.ts
As with quic, webtransport, and webrtc-direct.
> Don't include muxer and secure channel for webrtc

- multidim-interop/impl/js/.gitignore
- multidim-interop/impl/js/v0.45/BrowserDockerfile
- multidim-interop/impl/js/v0.45/Dockerfile
- multidim-interop/impl/js/v0.45/Makefile
- multidim-interop/versions.ts
#187 with an extra commit that fixes the builds from cache. The issue is that the browser images which are based on the node image for speed relied on the image being tagged with a certain name. When loading from cache we don't load the tag name again, just the image and reference it via the digest.
If we could reference base images by their digest that would have also fixed this issue.
> Reintroduce js-libp2p v0.45.0 and fix build from cache

- .github/workflows/multidim-interop.yml
This workflow uses the public cache. It just can't update it. The goal of this workflow is to see how public forks behave. The name is a vestige from when we didn't have a public cache. But the original goal was always to see how public forks and external repos would behave.
> Rename `build-without-cache` to `build-without-secrets`

- perf/impl/go-libp2p/v0.27/perf.go
- perf/impl/https/v0.1/main.go
Lots of nits. The biggest change here is that I refactored `sendBytes` and `drainStream` into pure functions, and copy-pasted them into the https implementation. Using an `io.MultiReader` allows us to simplify the reading of the `http.Request.Body`.
@mxinden Feel free to merge (this is targeting #184). Does this PR trigger a CI run? Would be good in order to see if this actually works.
> perf: simplify go-libp2p and https implementation

- perf/impl/https/v0.1/main.go
Small follow-up to https://github.com/libp2p/test-plans/pull/184.
> fix(perf/https): request downloadBytes instead of uploadBytes

- perf/impl/go-libp2p/v0.27/perf.go
Follow up to https://github.com/libp2p/test-plans/pull/184.
> fix(perf/go-libp2p): close write after sending in client

- perf/README.md
- perf/impl/go-libp2p/v0.27/main.go
- perf/impl/go-libp2p/v0.27/perf.go
- perf/impl/https/v0.1/main.go
- perf/impl/quic-go/v0.34/Makefile
- perf/impl/rust-libp2p-quinn/v0.52/Makefile
- perf/impl/rust-libp2p/v0.52/Makefile
- perf/runner/benchmark-results.json
Instead of exposing the time to establish a connection, the time to upload the bytes and the time to download the bytes, expose a single time including all three.
The rational here is, that differentiation of the three is flawed. E.g. when does one stop the upload timer and start the download timer? When the last byte is sent? When the last byte is flushed? When the first byte is received?
See https://github.com/libp2p/test-plans/pull/184#pullrequestreview-1482600521 for past discussion.
I will update the dashboard once this is merged.
Blocked on https://github.com/libp2p/rust-libp2p/pull/4105 and https://github.com/quic-go/perf/pull/12.
> refactor(perf): expose single latency measurement 

- multidim-interop/src/generator.ts
- multidim-interop/testplans.ts
- multidim-interop/versions.ts
Changes how imageIDs are loaded for a given version.
* imageID can now be a function that returns an imageID rather than directly a string.
* Defines a new canonical lookup function which matches how all current implementations are defined. A new implementation is not required to lay things out like this, but if it does it can reuse this function.
* imageIDs are now lazily loaded _after_ running the name-filter. This means, for example, if you only want to test WebTransport you don't have to build every implementation first.
This should make errors like [this](https://github.com/libp2p/test-plans/pull/206#discussion_r1240153895) harder to make. (I've made this error several times as well).
> Less error-prone way of defining image IDs and other quality of life improvements

- multidim-interop/src/generator.ts
A small cleanup to reduce duplication.
> cleanup: Squash queries down

- multidim-interop/src/compose-runner.ts
Ran into this new error: https://github.com/libp2p/test-plans/actions/runs/5466576345/jobs/9951702544#step:3:1256
The JSON.parse failed. Hard to debug if I don't know what the input was and the stdout of the nodes. This adds some helpful debug code.
> multidim interop: Add debug logging if JSON parse fails

- multidim-interop/impl/js/v0.45/BrowserDockerfile
- multidim-interop/impl/js/v0.45/Dockerfile
Improves caching for browsers on js-libp2p by installing playwright and browsers in the base image. This is the image that gets cached.
> interop: Install playwright in the base image so it is cached

- .github/workflows/perf.yml
- perf/runner/benchmark-results.json
- perf/runner/src/index.ts
- Increase upload/download benchmark iterations. Still conservative value of `10` due to slow rust-libp2p tcp. See https://github.com/libp2p/rust-yamux/issues/162. Note however that this is 10x an upload of 100MB.
- Increase latency benchmark iterations.
> fix(perf): increase iterations

- multidim-interop/package.json
- multidim-interop/src/compose-runner.ts
- multidim-interop/src/compose-stdout-helper.ts
First off, I don't really understand why compose split the line [here](https://github.com/libp2p/test-plans/actions/runs/5468772660/jobs/9956843684?pr=219#step:3:1199). It may be a bug in zig-libp2p, but there are no other callers of stdout (no race). And there's nothing fancy going on, it just writes to the stdout file the bytes directly (no buffering).
Whatever the reason, we should probably be a bit more resilient with parsing of the output compared to the initial regex. This adds a helper to help with parsing compose's output as well as a test case to make sure that we don't silently break this.
To avoid adding a whole new dependency on some test framework that opens the door to the nightmare of JS bundling, the test is a simple function that is run if you run the file directly (as …
> More resilient stdout parsing of dialer stdout

- .github/actions/run-interop-ping-test/action.yml
- multidim-interop/impl/rust/.gitignore
The cache works by mapping a set of inputs to a set out outputs. It fingerprints the inputs by looking at everything in the folder that isn't gitignored. The idea being that if it's ignored it's a build artifact and if it isn't than it is a build input. Since we didn't gitignore chromium-image.json it got treated as an input when we generated the fingerprint. This meant that the cache-key was different before the build and after the build.
I've added a check that will fail CI early if we detect a dirty Git tree after building. That should catch this class of errors.
This should fix the cache misses we've been seeing with rust-libp2p v0.52
> multidim-interop: Update rust-libp2p .gitignore with chromium-image.json

- multidim-interop/impl/js/v0.45/BrowserDockerfile
- multidim-interop/impl/js/v0.45/Dockerfile
Reverts libp2p/test-plans#226
Looking at this run has us downloading browsers on each interop test: https://github.com/libp2p/test-plans/actions/runs/5535076758/jobs/10100889429. I think what's happening is that playwright will helpfully (though not helpful in this case) download the latest browser. If we have an older browser because we cached it earlier then it will download a new one at run time.
By moving this back to the the post-cache build phase we download the browsers on every build yes, but hopefully avoid downloading them on every run.
I'll look at the CI logs to make sure that's the case.
> Revert "Install playwright in the base image so it is cached (#226)"

- .github/actions/run-interop-ping-test/action.yml
Exposes `--name-ignore` as `test-ignore` in the ping test github action to be consistent with how `--name-filter` is exposed as `test-filter`
Follow on from #225
> feat: expose name-ignore setting

- perf/impl/rust-libp2p/master/Makefile
- perf/runner/benchmark-results.json
- perf/runner/src/versions.ts
With https://github.com/libp2p/rust-libp2p/pull/3454 merged we can now test the new rust-libp2p QUIC implementation based on upstream quinn directly from rust-libp2p `master`.
This commit does the following in libp2p/test-plans:
1. Remove the `perf/impl/rust-libp2p-quinn` implementation.
2. Introduce the `perf/impl/rust-libp2p/master` version of the rust-libp2p implementation.
We can promote the latter to a proper version on the next rust-libp2p release.
> fix(perf): replace rust-libp2p-quinn/ with rust-libp2p/master

- perf/runner/benchmark-results.json
- perf/terraform/modules/long_lived/main.tf
- perf/terraform/modules/short_lived/main.tf
Multiple perf runs have failed due to "no space left on device". See e.g. https://github.com/libp2p/test-plans/actions/runs/5727165977/job/15527780097.
The perf terraform launch template previously did not specify a root volume size. Thus terraform used the default:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            25G  540K   25G   1% /run
/dev/nvme0n1p1  8.0G  1.9G  6.1G  24% /
tmpfs            63G     0   63G   0% /tmp
tmpfs            13G     0   13G   0% /run/user/1000
```
With this commit the root volume is increased to 100GB:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs            63G     0   63G   0% …
```
> fix(perf): increase root volume size

- perf/runner/benchmark-results.json
- perf/terraform/configs/remote/.terraform.lock.hcl
- perf/terraform/modules/long_lived/files/user-data.sh
- perf/terraform/modules/short_lived/main.tf
Previously only the maximum udp **receive** buffer size was increased to `2500000` bytes. With this commit both the send and the receive buffer size is increase.
> fix(perf): increase maximum udp send buffer size

- perf/runner/benchmark-results.json
- perf/terraform/modules/long_lived/main.tf
- perf/terraform/modules/short_lived/main.tf
Our perf terraform setup differentiates in long lived and short lived resources.
On CI, our long lived resources are spun up once and our short lived resources are spun up on each CI run. From time to time we have to adjust the long lived resources. End result is a new launch template that needs to be referenced in the short lived resources by version.
Next to our CI, the perf terraform setup can as well be used on personal AWS accounts. Their long lived launch template version likely doesn't match the configured launch template version of the short lived aws_instance.
Instead of specifying a specific version, instruct terraform to use the latest, thus supporting both our CI and personal AWS account use-case.
See also terraform `aws_instance` specification. …
> fix(perf): use `$Latest` launch template

- multidim-interop/versions.ts
The browser webrtc tests are too flaky. They've failed the last 6 master runs: https://github.com/libp2p/test-plans/actions/workflows/multidim-interop.yml?query=event%3Apush. 
I think we should remove them until we fix the flakiness issue (see #235).
> multidim-interop: Disable flaky browser webrtc tests

- perf/terraform/modules/long_lived/files/user-data.sh
On root the nvm install script can not find a shell config.
```
=> Profile not found. Tried ~/.bashrc, ~/.bash_profile, ~/.zprofile, ~/.zshrc, and ~/.profile.
```
> fix(perf): install nvm for ec2-user instead of root

- .github/workflows/multidim-interop.yml
Only run interop tests on changes to the multidim-interop/ directory (no use running them on changes to perf directory)
> ci: only run interop tests on changes to multidim-interop dir

- perf/README.md
- perf/runner/src/benchmark-result-type.ts
- perf/runner/src/index.ts
While integrating [the js impl of perf](https://github.com/libp2p/js-libp2p/pull/1604) I encountered some obstacles in running this infrastructure as well as adding and testing the _perf_ implementation. These are some improvements I thought would help new users of _perf_
Related https://github.com/libp2p/test-plans/issues/222
> feat(perf): Added new CLI flags for iterations + updated docs

- perf/impl/Makefile
- perf/runner/benchmark-results.json
- perf/runner/src/versions.ts
Implementation has been removed with https://github.com/libp2p/test-plans/pull/246.
> fix(perf): remove obsolete quinn build infra

- multidim-interop/README.md
1. js-libp2p uses a Makefile
2. The listener should be started first, then the dialer
> interop: fix description on how to run locally

- perf/terraform/configs/local/terraform.tf
- perf/terraform/modules/long_lived/main.tf
Instead of `m5n.8xlarge`, use `m7i.xlarge`.
Rational:
- Closer to real-world libp2p deployments (e.g. < 25 Gibps)
- Cheaper (~2 USD vs ~0.2 USD)
m5n.8xlarge:
- 32 vCPUs
- 128.0 GiB of memory
- 25 Gibps of bandwidth
- Intel Xeon Platinum 8259CL - 2019
m7i.xlarge:
- 4 vCPUs
- 16.0 GiB of memory
- up to 12.5 Gibps
- Intel Xeon Scalable (Sapphire Rapids) - 2023
> feat(perf): use m7i.xlarge

- perf/README.md
- perf/runner/src/index.ts
Follow up PR related to https://github.com/libp2p/test-plans/pull/258
Based on @mxinden 's [comments](https://github.com/libp2p/test-plans/pull/258#issuecomment-1691592573) regarding the perf runner
> fix: adjust cli flags for perf runner for testing purposes

- multidim-interop/impl/rust-chromium/.gitignore
- multidim-interop/impl/rust-chromium/v0.52/Makefile
- multidim-interop/versions.ts
The current caching implementation expects only a single docker container per implementation directory. This was not true for Rust `v0.52` which produced two containers: A native one and one with chromium and a WASM build.
Thus, the latter never got cached and we were rebuilding it on every run. By making it a separate implementation, the cache should be picked up again.
I refrained from extending the cache implementation to handle this because I think it would get too complicated.
Resolves: #301.
> fix: make `rust-chromium` a separate implementation

- hole-punch-interop/impl/rust/master/Makefile
- hole-punch-interop/versions.ts
The `v0.52` version string was really just a placeholder. Initially, I thought that we might merge https://github.com/libp2p/rust-libp2p/pull/4549 before the release cut-off for `v0.53` but that didn't happen.
To communicate this more clearly, we rename the current image to `rust-master`. We are also updating it to actually point _to_ a commit on master. Previously, it was pointing to a commit in https://github.com/libp2p/rust-libp2p/pull/4549. This new commit includes an important bug-fix (https://github.com/libp2p/rust-libp2p/pull/4747) that caused the QUIC hole-punch test to occasionally fail.
Once we cut the v0.53 release, this version should be promoted to that.
As a side-benefit, the new commit points to a version that includes the updated Dockerfile and allows the tests to be run …
> feat(hole-punch): update rust `v0.52` to `master`

- transport-interop/impl/java/v0.6/Makefile
- transport-interop/versions.ts
bring java transport-interop test up-to-date with latest changes
> transport-interop - add java-v0.6

- perf/impl/rust-libp2p/v0.53/Makefile
Update `perf/impl/rust-libp2p/v0.53` to rust-libp2p `v0.53.2`. With this patch release comes the rust-yamux stream receive window auto-tuning.
https://github.com/libp2p/rust-libp2p/pull/4970
https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-v0.53.2
> chore(perf): update to rust-libp2p v0.53.2

- perf/impl/rust-libp2p/v0.53/Makefile
Reverts libp2p/test-plans#339
The pull request was merged before the automated commit with the perf results. Thus reverting here. Sorry, I should have set it to draft.
> Revert "chore(perf): update to rust-libp2p v0.53.2"

- transport-interop/impl/nim/v1.0/Dockerfile
Because of nimble limitations - our package manager - the build can fail even though nothing changed. It can happen when new dependencies of libraries (that can be transitive) are released. We need to upgrade nim to fix the current build issue.
> chore(interop): update to nim 1.6.16

- transport-interop/src/compose-stdout-helper.ts
The test output can have occurrences of `{` that aren't the string we are looking for, eg:
```
dialer-1    | test browser
dialer-1    | [JavaScript Error: "Clear-Site-Data header found. Unknown value “"cache"”." {file: "http://127.0.0.1:34451/" line: 0}]
dialer-1    | [JavaScript Error: "Clear-Site-Data header forced the clean up of “cookies” data." {file: "http://127.0.0.1:34451/" line: 0}]
dialer-1    | [JavaScript Error: "Clear-Site-Data header forced the clean up of “storage” data." {file: "http://127.0.0.1:34451/" line: 0}]
```
These fail to parse so improve the results parsing by:
1. Try parsing every instance of `{...}` in the output, not just the first
2. Test the output for the `handshakePlusOneRTTMillis` and `pingRTTMilllis` keys
> fix: handle multiple strings that look like they might be JSON

- transport-interop/versionsInput.json
I'm removing webtransport from the older versions of go-libp2p so that when the next go-libp2p release comes out it doesn't run webtransport against older versions.
A bit more context here: https://github.com/libp2p/go-libp2p/issues/2789
> webtransport-go next release will be incompatible with older versions

- .github/actions/run-interop-hole-punch-test/action.yml
- .github/actions/run-interop-ping-test/action.yml
- .github/actions/run-transport-interop-test/action.yml
- .github/workflows/hole-punch-interop.yml
- .github/workflows/transport-interop.yml
- hole-punch-interop/helpers/cache.ts
- transport-interop/helpers/cache.ts
As we're setting up a new cache bucket, we'd like to be able to control its' configuration via GitHub vars/secrets fully.
> chore: parameterise s3 build cache setup

- .github/dependabot.yml
Only try to update deps for the latest js-libp2p version.
> fix: update dependabot to point to latest js release

- .github/actions/run-interop-hole-punch-test/action.yml
- .github/actions/run-interop-ping-test/action.yml
- .github/actions/run-transport-interop-test/action.yml
Node 18 is in maintenance mode and reaches EOL at the end of April so switch to evergreen LTS node.
> fix: use lts node

- .github/actions/run-transport-interop-test/action.yml
- .github/workflows/transport-interop.yml
The build-without-secrets flow was broken because it was trying to upload an empty results artifact to the same name as the interop test. This no longer works in upload-artifacts v4.
This fixes it by not uploading that empty file.
> fix: don't upload test results from build-only workflow. Support artifact suffixes

- .github/actions/run-transport-interop-test/action.yml
- transport-interop/impl/js/v1.x/Dockerfile
- transport-interop/impl/js/v1.x/test/dialer.spec.ts
- transport-interop/impl/js/v1.x/test/listener.spec.ts
- transport-interop/impl/js/v2.x/Dockerfile
- transport-interop/impl/js/v2.x/test/dialer.spec.ts
- transport-interop/impl/js/v2.x/test/listener.spec.ts
- transport-interop/src/compose-runner.ts
Pass a specified or default timeout to the ping operation in the js transport interop test implementation, otherwise the default timeout is used which may be too short for running under Docker in underpowered CI environments.
This can fix some perceived flakiness in test runs.
Also prints listening multiaddrs like other implementations.
> fix: apply timeout to ping in js tests

- transport-interop/impl/js/v1.x/BrowserDockerfile
- transport-interop/impl/js/v1.x/Dockerfile
- transport-interop/impl/js/v1.x/Makefile
- transport-interop/impl/js/v2.x/BrowserDockerfile
- transport-interop/impl/js/v2.x/Dockerfile
- transport-interop/impl/js/v2.x/Makefile
The default playwright image hasn't been updated for months so we end up removing and reinstalling browsers on every run, so use a specific version instead.
The playwright image comes with LTS node so we can base both the node and browser images off that and save having to build the images over and over again.
Before:
After:
> fix: use latest playwright image

- .github/workflows/perf.yml
- perf/terraform/modules/ci/cleanup.tf
- perf/terraform/modules/ci/test/cleanup.yml
This increases the timeout for resource cleanup in perf tests to 6 hours, which is the equivalent of max job execution time in GitHub Actions.
> chore: increase the timeout for resource cleanup in perf tests

- transport-interop/impl/nim/v1.0/Dockerfile
for some reason the incorrect nim docker image is being pulled in other PRs. i am testing if specifying a known-good version of the image via the hash will fix this.
> specify known-good image by hash to force the correct version

- .github/actions/run-transport-interop-test/action.yml
- .github/workflows/transport-interop.yml
- transport-interop/impl/java/v0.9/Makefile
- transport-interop/src/generator.ts
- transport-interop/testplans.ts
- transport-interop/versionsInput.json
from @kevodwyer:
> Have confirmed test results locally (at least those implementation that will build on apple m2 - go, rust, java, js).
> Zig - uses ed25519 certs which netty quic doesn't support - https://github.com/netty/netty-incubator-codec-quic/issues/487
>
> The Nim build error seems unrelated to this PR.
This is a PR from a local copy of the branch on the fork: https://github.com/kevodwyer/test-plans/tree/feat/java-v0.9
I did this so that the checks will have access to the secrets and we can get a clean CI/CD pass.
This is in lieu of #638
> Feat/java v0.9

- transport-interop/versionsInput.json
It's causing an issue with jvm-libp2p. I need to debug it more, but don't want to block getting jvm-libp2p in the transport interop tester.
> Disable Zig in transport-interop

- transport-interop/impl/jvm/.gitignore
- transport-interop/impl/jvm/v1.2/Makefile
- transport-interop/versionsInput.json
Adding the standard jvm-libp2p (https://github.com/libp2p/jvm-libp2p) to the test suite.
For now, I am only adding a subset of transport and muxers to validate that we are properly running the tests. Once we are happy with it, I'll add other options.
> Add jvm-libp2p to protocol interop suite

- .github/workflows/hole-punch-interop.yml
- .github/workflows/transport-interop.yml
This PR removes usage of self-hosted runners from the test-interop job.
It is part of libp2p DX services offboarding initiative.
> ci: remove usage of self-hosted runners
