dht/compositions/all-balsam-k8s.toml, dht/compositions/all-both-k8s.toml, dht/compositions/all-cypress-k8s.toml, dht/compositions/bootstrap-network-cypress-k8s.toml, dht/compositions/find-provs-balsam-k8s.toml, dht/compositions/find-provs-both-k8s.toml, dht/compositions/find-provs-both-local.toml, dht/compositions/find-provs-cypress-k8s.toml, dht/compositions/gcp-cypress-k8s.toml
Related https://github.com/testground/testground/pull/971
=> use selectors, not Selectors

.github/workflows/run-composition.yml
Remove the TEST commit from https://github.com/libp2p/test-plans/pull/23.
=> ci: remove test commit

ping/rust/src/main.rs
- Don't log every `SwarmEvent`.
- Log connected and ping only once per peer.
- Log format somewhat consistent with Golang implementation.
=> ping/rust/src/main: Reduce noise on logs

ping/rust/src/main.rs
This will speed up test runs.
What do folks think?
=> ping/rust/src/main: Decrease ping interval

ping/_compositions/go-rust-interop-latest.toml, ping/_compositions/go-rust-interop.toml, ping/_compositions/rust-cross-versions.toml
This fixes problems such as https://github.com/libp2p/rust-libp2p/actions/runs/3502660159/jobs/5867194298#step:6:599 and possibly others.
cc @mxinden @jxs
=> fix(ping/rust): Bad typos

ping/rust/Dockerfile
Follow up to https://github.com/libp2p/test-plans/pull/79/. See discussion https://github.com/libp2p/test-plans/pull/79#discussion_r1030337736.
=> fix(ping/rust): Only specify branch when building master

ping/_compositions/rust.toml, ping/rust/Cargo.toml, ping/rust/src/bin/testplan_0451.rs, ping/rust/src/bin/testplan_0461.rs
to 0.45.1 and 0.46.1 respectively.
=> ping: update Rust versions 0.45.0 and 0.46.0

ping/rust/Dockerfile, ping/rust/src/main.rs
=> feat(ping/rust): Cache built dependencies in separate docker layer

.github/workflows/multidim-interop.yml, .github/workflows/run-testplans.yml, multidim-interop/dockerBuildWrapper.sh, multidim-interop/versions.ts
=> Cache builds with s3 buckets

multidim-interop/js/v0.41/package-lock.json, multidim-interop/js/v0.41/package.json, multidim-interop/js/v0.41/test/ping.spec.ts, multidim-interop/src/generator.ts, multidim-interop/versions.ts
Currently only testing chrome -> rust over webrtc
=> Add Browser WebRTC test

multidim-interop/src/lib.ts
=> Add key to table

multidim-interop/nim/v1.0/.gitignore
Ignores some files that are generated by the Makefile.
=> Add .gitignore for nim

multidim-interop/README.md
In debugging https://github.com/libp2p/rust-libp2p/pull/3013 I found it a bit difficult as a newcomer to get started with this repo. This PR just serves to clarify how one could get started running this locally.
Welcome to any feedback on how this could be better articulated.
Thanks to @MarcoPolo on how to get this instance running.
=> docs: update readme for instructions on running locally

multidim-interop/Makefile, multidim-interop/impl/java/.gitignore, multidim-interop/impl/java/v0.0.1/Makefile, multidim-interop/versions.ts
all java impl tests pass in both directions
=> add Java to interop tests

multidim-interop/impl/java/v0.0.1/Makefile
Remove incorrectly calling node.stop() twice
commit: https://github.com/Peergos/nabu/commit/6fad470c92a5c4ab368bc615e64dbf40b5ff9ccb
=> fix(java-libp2p): update test client with resource fix

perf/README.md
Minor change documenting status quo. I will merge right away. Happy to do follow-ups.
=> chore(perf): document GitHub action usage

multidim-interop/src/generator.ts, multidim-interop/testplans.ts
=> multidim-interop: Add name ignore option

multidim-interop/impl/go/v0.29/Makefile, multidim-interop/impl/go/v0.29/version.lock
Adds go-libp2p v0.29.0
@marten-seemann might like that it also closes #193
=> Add go-libp2p v0.29.0

perf/runner/benchmark-results.json, perf/terraform/modules/long_lived/files/user-data.sh
Needed for js-libp2p perf implementation.
https://github.com/libp2p/test-plans/pull/244/
=> chore(perf): install NodeJS LTS on VMs

.github/workflows/add-new-impl-versions.yml
This is a follow-up to https://github.com/libp2p/test-plans/pull/349
=> feat: add new implementation versions (js, rust)

transport-interop/impl/js/v0.45/Makefile, transport-interop/impl/js/v0.46/Makefile, transport-interop/impl/js/v1.x/Makefile, transport-interop/impl/js/v2.x/Makefile
Removes any cached layers before building.
=> fix: prune layer cache before build

.github/actions/run-interop-hole-punch-test/action.yml, .github/actions/run-interop-ping-test/action.yml, .github/actions/run-perf-benchmark/action.yml, .github/actions/run-transport-interop-test/action.yml
=> ci: update actions/upload-artifact to v4
